name: Python Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |# 👇 找到原本的這一段，在中間補上 env 區塊
    - name: Run Python script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python update_finance.py
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python script
      run: python update_finance.py
